name: "Android Build"

on:
  workflow_call:
    inputs:
      publish:
        required: false
        type: boolean
        description: Publish to Appcenter
env:
  ARTIFACT_NAME: LearnCICDRN.aab
jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install Node modules
        run: yarn install --frozen-lockfile
      - name: Cache Gradle Wrapper
        uses: actions/cache@v4
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: Cache Gradle Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-
      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew
      - name: Сделать билд
        run: |
          cd android && ./gradlew bundleRelease --no-daemon
      - name: Upload build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: "${{ env.ARTIFACT_NAME }}"
          path: "android/app/build/outputs/bundle/release/app-release.aab"

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: "${{ env.ARTIFACT_NAME }}"

  publish_to_appcenter:
    if: ${{ inputs.publish == true }}
    runs-on: ubuntu-latest
    needs: build_android
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: "${{ env.ARTIFACT_NAME }}"
          path: "android/"
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 1.8
          distribution: 'oracle'

      - name: Upload artifact to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: AppKlaar/LearnCICDRN-Android # Required, username followed by App name
          token: ${{secrets.APP_CENTER_TOKEN_ANDROID}} # upload token
          group: Testers # Distribution group (or multiple groups split by ; delimiter)
          file: android/app-release.aab # Required Artifact to upload (.apk or .ipa)
          notifyTesters: true
          debug: false

      # - name: Upload app to Google Play
      #   uses: r0adkll/upload-google-play@v1
      #   with:
      #     serviceAccountJsonPlainText: ${{ SERVICE_ACCOUNT_JSON }} # !!! Добавить
      #     packageName: com.example.MyApp # !!!! Зарегать packageName
      #     releaseFiles: android/app-release.aab
      #     track: production