name: Build react native app and deploy it
on: 
  workflow_dispatch:
  push:
    branches:
      - 'main'
    # paths-ignore:
    #   - '.github/workflows/*' # не запускать воркфлоу при обновлении самих воркфлоу
jobs:
  Install_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn' # Кэшировать зависимости
      - name: Install node modules
        run: yarn install --frozen-lockfile # Означает что будут установлены строго те зависимости, что указаны в yarn.lock

  Bump_Android_and_iOS_versions:
    runs-on: ubuntu-latest
    needs: Install_and_test
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install Node modules
        run: yarn install --frozen-lockfile
      - name: Sync React Native version with package.json version
        run: npx react-native-version
      - name: Commit version sync changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: react native - android & ios versions updated"
  Build_ios:
    needs: Bump_Android_and_iOS_versions
    uses: ./.github/workflows/ios_build.yml
    secrets: inherit # It is important, otherwise the secrets referred in those files won’t get populated
  Build_android:
    needs: Bump_Android_and_iOS_versions
    uses: ./.github/workflows/android_build.yml
    secrets: inherit