name: "iOS Build"
on:
  workflow_call:
    inputs:
      publish:
        required: false
        type: boolean
        description: Publish to Appcenter
    secrets:
      P12_BASE64:
        required: true
      MOBILEPROVISION_BASE64:
        required: true
      IOS_TEAM_ID:
        required: true
      CERTIFICATE_PASSWORD:
        required: true
      NPM_TOKEN:
        required: true
      APP_CENTER_TOKEN_IOS:
        required: true

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install node modules
        run: yarn install --frozen-lockfile
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6.10' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Restore Pods cache
        uses: actions/cache@v4
        with:
          path: |
            ios/Pods
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }} # Ключ для кэша
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Install pod dependencies
        run: cd ios && pod install && cd ..
      - name: Build iOS (Release)
        uses: yukiarrr/ios-build-action@v1.11.2
        with:
          project-path: ios/appklaartemplv3.xcodeproj
          workspace-path: ios/appklaartemplv3.xcworkspace # optional
          p12-base64: ${{ secrets.P12_BASE64 }}
          mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
          code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
          certificate-password: ${{ secrets.CERTIFICATE_PASSWORD }}
          team-id: ${{ secrets.IOS_TEAM_ID }}
          output-path: "PackPawer.ipa"
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          path: "PackPawer.ipa"
          name: "PackPawer.ipa"